# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html


# Amy runs on PostgreSQL, please fill out the following section:
amy_editor:
  # adapter: postgresql
  # database: amy_editor_development
  # encoding: unicode
  # username: p
  # password: 

  adapter: mysql
  database: amy_editor
  username: root
  password: whoa
  encoding: utf8
  host: localhost


# This is your standard configuration, Amy won't interfere with that:
development:
  adapter: mysql
  database: yourapp_development
  username: root
  password:
  encoding: utf8
  host: localhost

# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
test:
  adapter: mysql
  database: yourapp_test
  username: root
  password:
  encoding: utf8
  host: localhost

production:
  adapter: mysql
  database: yourapp_production
  username: root
  password:
  encoding: utf8
  host: localhost
